
services:
  postgres:
    image: postgres:latest
    container_name: whatsapp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp_api