version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: wpp_cal_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wpp_cal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wpp_cal_network

  redis:
    image: redis:7
    container_name: wpp_cal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - wpp_cal_network

networks:
  wpp_cal_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
