### Variáveis
@baseUrl = http://localhost:3000/api/v1
@phone = 5585998546812
@companyId = 1
@token = 
@channelId = 7



####################### Login com usuário admin
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

### Salvar token da resposta
@token = {{login.response.body.access_token}}

### Listar usuários
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Buscar usuário por ID
GET {{baseUrl}}/users/2
Authorization: Bearer {{token}}

### Criar novo usuário
POST {{baseUrl}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "123456",
  "companyId": 1,
  "active": true
}

### Atualizar usuário
PATCH {{baseUrl}}/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Teste Atualizado",
  "active": false
}

### Deletar usuário
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{token}}

### Buscar informações do usuário logado
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}} 


### 1. Autenticar com Meta/Facebook e salvar credenciais
POST {{baseUrl}}/whatsapp/auth?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientId": "1195822431721175",
  "clientSecret": "d798febfecd75842168691f20d7aa7ae",
  "fbExchangeToken": "EAAQZCmBtB1tcBOZBJXMw6krK1Gj2ce6bORfZC4w2ZC0N3mzVOmMZC1eIXxKTZC6uVIGdXoB4q47LmzarwOBbxHVl1bC8gZAqP1nH87OLuhLbNsQXgQtTAON3oOy0qwPZBf1ZATaCMFwT79OmqTEYpPkfGSrmnUoroIwK1EGoY8U2WG3rWE3wiD3z0eibltCeHKJqImHvfYMnmNoANcAZDZD"
}

### 2. Atualizar credenciais
PATCH {{baseUrl}}/whatsapp/auth/1?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientId": "1195822431721175",
  "clientSecret": "d798febfecd75842168691f20d7aa7ae",
  "fbExchangeToken": "EAAQZCmBtB1tcBOZBJXMw6krK1Gj2ce6bORfZC4w2ZC0N3mzVOmMZC1eIXxKTZC6uVIGdXoB4q47LmzarwOBbxHVl1bC8gZAqP1nH87OLuhLbNsQXgQtTAON3oOy0qwPZBf1ZATaCMFwT79OmqTEYpPkfGSrmnUoroIwK1EGoY8U2WG3rWE3wiD3z0eibltCeHKJqImHvfYMnmNoANcAZDZD"
}


### 3. Listar histórico de autenticação
GET {{baseUrl}}/whatsapp/auth/history?companyId={{companyId}}
Authorization: Bearer {{token}}





####################### Canais do WhatsApp (TESTADO E FUNCIONANDO) #######################

### 1. Criar novo canal
POST {{baseUrl}}/whatsapp/channels
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Canal Principal 11",
  "number": "15551489509",
  "description": "Canal principal da empresa",
  "companyId": {{companyId}},
  "departmentId": 1,
  "isDefault": true,
  "whatsappCredentialId": 1,
  "type": "WHATSAPP_CLOUD",
  "fbNumberPhoneId": "622608514273316",
  "accountWBId": "1515202096105724"
}

### 2. Listar todos os canais
GET {{baseUrl}}/whatsapp/channels?companyId={{companyId}}
Authorization: Bearer {{token}}

### 3. Buscar canal específico
GET {{baseUrl}}/whatsapp/channels/7?companyId={{companyId}}
Authorization: Bearer {{token}}

### 4. Conectar canal
PATCH {{baseUrl}}/whatsapp/channels/7/connect?companyId={{companyId}}
Authorization: Bearer {{token}}

### 5. Desconectar canal
PATCH {{baseUrl}}/whatsapp/channels/7/disconnect?companyId={{companyId}}
Authorization: Bearer {{token}}

### 6. Status do canal
GET {{baseUrl}}/whatsapp/channels/7/status?companyId={{companyId}}
Authorization: Bearer {{token}}

### 7. Remover canal
DELETE {{baseUrl}}/whatsapp/channels/11?companyId={{companyId}}
Authorization: Bearer {{token}}




####################### CONTATOS #######################

### 1. Criar novo contato
POST {{baseUrl}}/contacts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "João Silva",
  "phone": "5511999999999",
  "email": "joao@example.com",
  "gender": "M",
  "avatarUrl": "https://example.com/avatar.jpg",
  "city": "São Paulo",
  "state": "SP",
  "address": "Rua Example, 123",
  "complement": "Apto 42",
  "zipCode": "01234-567",
  "country": "Brasil"
}

### Listar todos os contatos (paginado)
GET {{baseUrl}}/contacts?page=1&take=10&order=asc
Authorization: Bearer {{token}}

### Buscar contatos (paginado)
GET {{baseUrl}}/contacts?search=joao&page=1&take=10&order=asc
Authorization: Bearer {{token}}

### Buscar um contato específico
GET {{baseUrl}}/contacts/1
Authorization: Bearer {{token}}

### Atualizar um contato
PATCH {{baseUrl}}/contacts/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "João Silva Atualizado",
  "email": "joao.novo@example.com",
  "gender": "M",
  "avatarUrl": "https://example.com/new-avatar.jpg",
  "city": "Rio de Janeiro",
  "state": "RJ",
  "address": "Av Example, 456",
  "complement": "Sala 101",
  "zipCode": "04321-765",
  "country": "Brasil"
}

### Deletar um contato
DELETE {{baseUrl}}/contacts/1
Authorization: Bearer {{token}} 




####################### MENSAGENS #######################
### Enviar mensagem de texto
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/send?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "to": "5585998546812",
  "type": "text",
  "text": "Olá, como posso ajudar? novamente"
}

### Enviar imagem
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/send?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "to": "5585998546812",
  "type": "image",
  "mediaUrl": "https://www.adobe.com/br/express/feature/image/remove-background/png/media_142f9cf5285c2cdcda8375c1041d273a3f0383e5f.png?width=2000&format=webply&optimize=medium",
  "caption": "Foto do produto"
}

### Enviar documento
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/send?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "to": "5585998546812",
  "type": "document",
  "mediaUrl": "https://example.com/doc.pdf",
  "filename": "contrato.pdf",
  "caption": "Contrato de serviço"
}

### Enviar áudio
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/send?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "to": "5585998546812",
  "type": "audio",
  "mediaUrl": "https://example.com/audio.mp3"
}

### Enviar vídeo
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/send?companyId={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "to": "5585998546812",
  "type": "video",
  "mediaUrl": "https://example.com/video.mp4",
  "caption": "Tutorial do produto"
}

### Consultar histórico de mensagens por telefone
GET {{baseUrl}}/whatsapp/messages/phone/5585998546812?companyId={{companyId}}
Authorization: Bearer {{token}}

### Consultar mensagem específica
GET {{baseUrl}}/whatsapp/messages/wamid.HBgMNTU4NTk4NTQ2ODEyFQIAEhggODY2MjZEMEYzMkJDQUUyQTE2OERDMjhGRThBREQ4MjQA
Authorization: Bearer {{token}}

### Consultar mensagens por canal
GET {{baseUrl}}/whatsapp/messages/channel/{{channelId}}?companyId={{companyId}}
Authorization: Bearer {{token}}

### Consultar mensagens por ticket
GET {{baseUrl}}/whatsapp/messages/ticket/5?companyId={{companyId}}
Authorization: Bearer {{token}}

### Marcar mensagens do contato como lidas 
### TODO: tem que marcar com não lido do contato e não do channel
POST {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/mark-as-read
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "phone": "5585998546812"
}

### Consultar o número de mensagens não lidas
GET {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/unread-count?phone=5585998546812
Authorization: Bearer {{token}}

### Listar contatos com mensagens
GET {{baseUrl}}/whatsapp/messages/channel/{{channelId}}/contacts?companyId={{companyId}}
Authorization: Bearer {{token}} 




####################### TICKETS #######################

### Transferir ticket para outro atendente
POST {{baseUrl}}/whatsapp/tickets/1/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "USER",
  "fromId": 1,
  "toId": 2,
  "reason": "Atendente em horário de almoço"
}

### Transferir ticket para outro departamento
POST {{baseUrl}}/whatsapp/tickets/5/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "DEPARTMENT",
  "fromId": 1,
  "toId": 4,
  "reason": "Cliente solicitou falar com suporte técnico"
}

### Transferir ticket para outro canal
POST {{baseUrl}}/whatsapp/tickets/1/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "CHANNEL",
  "fromId": 1,
  "toId": 2,
  "reason": "Canal principal em manutenção"
}

### Listar histórico de transferências do ticket
GET {{baseUrl}}/whatsapp/tickets/5/transfers
Authorization: Bearer {{token}} 

### Adicionar nota ao ticket
POST {{baseUrl}}/whatsapp/tickets/5/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Cliente solicitou mais informações sobre o produto X. Preciso verificar com o setor de vendas."
}
