export enum WhatsappStatus {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR',
  QRCODE = 'QRCODE',
  STARTING = 'STARTING',
  READY = 'READY'
} 